name: nationalparks

on: 
  workflow_dispatch:

env:
  CONFIG_FILE_PATH: ./env-config.txt # Path to the configuration file.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Load Environment Variables
      run: |
        set -a # Enable exporting all variables
        source $CONFIG_FILE_PATH
        set +a

    - name: Install Podman and Skopeo
      run: |
        sudo apt-get update
        sudo apt-get -y install podman skopeo

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        
    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Login to OpenShift
      env:
        OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
        OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      run: |
        oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify

    - name: Authenticate Podman to ECR
      env:
        AWS_REGION: $AWS_REGION
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        aws ecr get-login-password --region $AWS_REGION | podman login --username AWS --password-stdin $ECR_URL

    - name: Build Application
      run: |
        oc project $OPENSHIFT_PROJECT
        oc new-app $BASE_IMAGE~$REPO_URL --name=$BUILD_NAME

    - name: Tag Podman Image for ECR
      run: |
        podman tag $BUILD_NAME:latest $ECR_URL/$BUILD_NAME:latest

    - name: Push Image to ECR with Skopeo
      run: |
        skopeo copy --dest-creds AWS:${{ secrets.AWS_SECRET_ACCESS_KEY }} containers-storage:$BUILD_NAME:latest docker://$ECR_URL/$BUILD_NAME:latest

    - name: Deploy Application in OpenShift
      run: |
        oc new-app $ECR_URL/$BUILD_NAME:latest --name=$BUILD_NAME

    - name: Check Deployment Status
      run: |
        oc status

    - name: Expose Service
      run: |
        oc expose svc $BUILD_NAME
