name: nationalparks

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Podman and Skopeo
      run: |
        sudo apt-get update
        sudo apt-get -y install podman skopeo

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update


    - name: Authenticate Podman to ECR
      env:
        AWS_REGION: us-east-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        aws ecr get-login-password --region $AWS_REGION | podman login --username AWS --password-stdin 677628568568.dkr.ecr.us-east-2.amazonaws.com
    - name: Build Application
      run: |
        oc project parksmap
        oc new-app registry.access.redhat.com/ubi9/openjdk-17~https://github.com/sansow/nationalparks --name=nationalparks

    - name: Tag Podman Image for ECR
      run: |
        podman tag nationalparks:latest 677628568568.dkr.ecr.us-east-2.amazonaws.com/nationalparks:latest

    - name: Push Image to ECR with Skopeo
      run: |
        skopeo copy --dest-creds AWS:${{ secrets.AWS_SECRET_ACCESS_KEY }} containers-storage:nationalparks:latest docker://677628568568.dkr.ecr.us-east-2.amazonaws.com/nationalparks:latest

    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Login to OpenShift
      env:
        OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
        OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      run: |
        oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify

    - name: Deploy Application in OpenShift
      run: |
        oc new-app 677628568568.dkr.ecr.us-east-2.amazonaws.com/nationalparks:latest --name=nationalparks

    - name: Check Deployment Status
      run: |
        oc status

    - name: Expose Service
      run: |
        oc expose svc nationalparks
